// <auto-generated />
using Ecommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Ecommerce.Models.BannerItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BannerItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltText = "Diskon Besar",
                            ImageUrl = "/images/banner1.jng",
                            LinkUrl = "/Product?searchQuery=Diskon"
                        },
                        new
                        {
                            Id = 2,
                            AltText = "Produk Terbaru",
                            ImageUrl = "/images/banner2.jpg",
                            LinkUrl = "/Product?categoryId=1"
                        },
                        new
                        {
                            Id = 3,
                            AltText = "Gratis Ongkir",
                            ImageUrl = "/images/banner3.jpg",
                            LinkUrl = "#"
                        });
                });

            modelBuilder.Entity("Ecommerce.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogoUrl = "/images/asus_logo.png",
                            Name = "Asus"
                        },
                        new
                        {
                            Id = 2,
                            LogoUrl = "/images/samsung_logo.jpg",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 3,
                            LogoUrl = "/images/logitech_logo.png",
                            Name = "Logitech"
                        },
                        new
                        {
                            Id = 4,
                            LogoUrl = "/images/apple_logo.svg",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 5,
                            LogoUrl = "/images/xiaomi_logo.png",
                            Name = "Xiaomi"
                        });
                });

            modelBuilder.Entity("Ecommerce.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/laptop.png",
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/handphone.jpg",
                            Name = "Handphone"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/headset.jpg",
                            Name = "Headset"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/keyboard.jpg",
                            Name = "Keyboard"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/images/mouse.jpg",
                            Name = "Mouse"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/images/charger.jpg",
                            Name = "Charger"
                        });
                });

            modelBuilder.Entity("Ecommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            BrandName = "",
                            CategoryId = 1,
                            CategoryName = "",
                            Description = "Laptop gaming terbaik",
                            ImageUrl = "/images/rog_strix.jpg",
                            Name = "Laptop ROG Strix",
                            Price = 25000000m
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 4,
                            BrandName = "",
                            CategoryId = 2,
                            CategoryName = "",
                            Description = "Handphone canggih",
                            ImageUrl = "/images/iphone_15_pro.png",
                            Name = "iPhone 15 Pro",
                            Price = 20000000m
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            BrandName = "",
                            CategoryId = 3,
                            CategoryName = "",
                            Description = "Headset gaming pro",
                            ImageUrl = "/images/logitech_g_pro_x.jpeg",
                            Name = "Logitech G Pro X",
                            Price = 1500000m
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 3,
                            BrandName = "",
                            CategoryId = 4,
                            CategoryName = "",
                            Description = "Keyboard mekanikal",
                            ImageUrl = "/images/keyboard_k2.gif",
                            Name = "Keyboard Mechanical K2",
                            Price = 800000m
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            BrandName = "",
                            CategoryId = 2,
                            CategoryName = "",
                            Description = "Flagship Samsung",
                            ImageUrl = "/images/samsung_s23.png",
                            Name = "Samsung Galaxy S23",
                            Price = 15000000m
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 3,
                            BrandName = "",
                            CategoryId = 5,
                            CategoryName = "",
                            Description = "Mouse presisi tinggi",
                            ImageUrl = "/images/logitech_g502.bmp",
                            Name = "Mouse Gaming G502",
                            Price = 750000m
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 5,
                            BrandName = "",
                            CategoryId = 6,
                            CategoryName = "",
                            Description = "Charger cepat",
                            ImageUrl = "/images/anker_charger.webp",
                            Name = "Charger Anker 65W",
                            Price = 300000m
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 4,
                            BrandName = "",
                            CategoryId = 1,
                            CategoryName = "",
                            Description = "Laptop tipis dan bertenaga",
                            ImageUrl = "/images/macbook_air_m2.jpg",
                            Name = "Macbook Air M2",
                            Price = 18000000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
